version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
