version: '3'

services:
  backend:
    build: 
      context: ./backend  
      dockerfile: Dockerfile 
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: ./django-setup.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  # frontend:

  db:
    image: postgres    
    environment:
      POSTGRES_DB: NAME
      POSTGRES_USER: USER_POSTGRES
      POSTGRES_PASSWORD: PASSWORD_POSTGRES
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    container_name: HOST
    ports:
      - '5432:5432'
    env_file:
      - .env
    command: ["docker-entrypoint.sh", "postgres"]

  volumes:
    pgdata:
    # redis_data: