# Generated by Django 5.0.1 on 2024-01-14 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_customtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomToken",
        ),
    ]
