# Generated by Django 5.0.1 on 2024-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_customuser_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, default="John", max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, default="Doe", max_length=150),
        ),
    ]
