# Generated by Django 5.0.1 on 2024-01-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_customuser_role_alter_customuser_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_loggin",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
