# Generated by Django 5.0.1 on 2024-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_profile_is_configured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.FileField(upload_to="photos/%Y/%m/%d/"),
        ),
    ]
