# Generated by Django 5.0.1 on 2024-04-28 13:16

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.FileField(
                default="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/340px-Default_pfp.svg.png",
                upload_to="photos/%Y/%m/%d/",
                validators=[user.models.validate_file_size],
            ),
        ),
    ]
