# Generated by Django 5.0.1 on 2024-04-29 20:39

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.FileField(
                upload_to="photos/%Y/%m/%d/",
                validators=[user.models.validate_file_size],
            ),
        ),
    ]
