# Generated by Django 5.0.1 on 2024-01-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminx", "0001_initial"),
        ("task", "0009_task_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("create", "Create"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="task.comment",
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="task.project",
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="task.task",
            ),
        ),
    ]
