# Generated by Django 5.0.1 on 2024-02-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminx", "0008_contactform"),
        ("drf_api_logger", "0002_auto_20211221_2155"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAPILogsModel",
            fields=[
                (
                    "apilogsmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drf_api_logger.apilogsmodel",
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=255, null=True)),
                ("model_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Custom API Log",
                "verbose_name_plural": "Custom API Logs",
                "db_table": "custom_drf_api_logs",
            },
            bases=("drf_api_logger.apilogsmodel",),
        ),
    ]
