# Generated by Django 5.0.1 on 2024-02-20 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminx", "0009_customapilogsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomAPILogsModel",
        ),
    ]
