# Generated by Django 5.0.1 on 2024-02-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminx", "0010_delete_customapilogsmodel"),
        ("task", "0026_alter_attachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changelog",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task.comment",
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task.project",
            ),
        ),
        migrations.AlterField(
            model_name="changelog",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="task.task"
            ),
        ),
    ]
