# Generated by Django 5.0.1 on 2024-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customtags",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
