type User = {
  id:string;
  firstName: string;
  lastName: string;
  gender: string;
  email: string;
  phone: string;
  userAvatar: string;
  role: string;
  createdAt: string;
  active: boolean;
};

export const User: User = {
  id:"1",
  firstName: "John",
  lastName: "Doe",
  gender: "male",
  email: "JDoe@gmail.com",
  phone: "25321532",
  userAvatar: "./src/img/seller2.jpg",
  role: "Admin",
  createdAt: "22/04/2023",
  active: true,
};

export const contributors: User[] = [
  {
    id:"2",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"3",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"4",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"5",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"6",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"7",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"8",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"9",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"10",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"11",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
  {
    id:"12",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "User",
    createdAt: "22/04/2023",
    active: false,
  },
  {
    id:"13",
    firstName: "Jane",
    lastName: "Jackson",
    gender: "female",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/woman.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: false,
  },
  {
    id:"14",
    firstName: "John",
    lastName: "Doe",
    gender: "male",
    email: "JDoe@gmail.com",
    phone: "25321532",
    userAvatar: "./src/img/seller2.jpg",
    role: "Admin",
    createdAt: "22/04/2023",
    active: true,
  },
];

