# Generated by Django 5.0.1 on 2024-01-09 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attachment",
            new_name="Attachement",
        ),
    ]
