# Generated by Django 5.0.1 on 2024-01-09 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_rename_attachment_attachement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attachement",
            new_name="Attachment",
        ),
    ]
