# Generated by Django 5.0.1 on 2024-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=10,
            ),
        ),
    ]
