# Generated by Django 5.0.1 on 2024-01-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_project_tags_project_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("blocked", "Blocked"),
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
