# Generated by Django 5.0.1 on 2024-01-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0005_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="task.comment",
            ),
        ),
    ]
