# Generated by Django 5.0.1 on 2024-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0006_attachment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
