# Generated by Django 5.0.1 on 2024-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0007_alter_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("blocked", "Blocked"),
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
