# Generated by Django 5.0.1 on 2024-01-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0008_project_archive_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
