# Generated by Django 5.0.1 on 2024-01-24 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0012_task_created_by_task_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
