# Generated by Django 5.0.1 on 2024-01-25 19:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("task", "0014_remove_comment_creator_comment_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
