# Generated by Django 5.0.1 on 2024-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0016_alter_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("bug", "Bug"),
                    ("feature", "Feature"),
                    ("question", "Question"),
                    ("improvement", "Improvement"),
                    ("other", "Other"),
                ],
                default="question",
                max_length=20,
            ),
        ),
    ]
