# Generated by Django 5.0.1 on 2024-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0017_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(upload_to="attachments/%Y/%m/%d/"),
        ),
    ]
