# Generated by Django 5.0.1 on 2024-02-07 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0018_alter_attachment_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
    ]
