# Generated by Django 5.0.1 on 2024-02-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("task", "0019_remove_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.ManyToManyField(blank=True, to="tags.customtags"),
        ),
    ]
