# Generated by Django 5.0.1 on 2024-02-08 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0020_project_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tag",
            new_name="tags",
        ),
    ]
