# Generated by Django 5.0.1 on 2024-02-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0022_alter_project_status_alter_task_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="task_task_title_a04b80_idx",
            old_name="task_task_title_f93335_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.IntegerField(null=True),
        ),
    ]
