# Generated by Django 5.0.1 on 2024-02-20 15:16

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0025_remove_task_assignees_task_assignees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(
                upload_to="attachments/%Y/%m/%d/",
                validators=[task.models.validate_file_size],
            ),
        ),
    ]
